# Generated by Django 5.0.6 on 2024-06-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_facebook_teacher_githubaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='githubaa',
            new_name='github',
        ),
    ]
