# Generated by Django 5.0.6 on 2024-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/defaultImage.png', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
